### ISSUE TITLE
The customization of  the storage size of the etcd lockserver doesn't work

### ISSUE THREAD

**Issue by PinZhang** [planetscale/vitess-operator#117]
Added the following configuration to cell:
```yaml
  cells:                                                                                                                                                       
  - name: samplecell                                                                                                                                        
    lockserver:                                                                                                                                                
      etcd:                                                                                                                                                    
        createClientService: true                                                                                                                              
        createPDB: true                                                                                                                                        
        createPeerService: true                                                                                                                                
        dataVolumeClaimTemplate:                                                                                                                               
          accessModes:                                                                                                                                         
          - ReadWriteOnce                                                                                                                                      
          dataSource: null                                                                                                                                     
          resources:                                                                                                                                           
            requests:                                                                                                                                          
              storage: 20Gi                                                                                                                                    
        image: quay.io/coreos/etcd:v3.3.13                                                                                                                     
        resources:                                                                                                                                             
          limits:                                                                                                                                              
            memory: 256Mi                                                                                                                                      
          requests:                                                                                                                                            
            cpu: 100m                                                                                                                                          
            memory: 256Mi
```
here is the generated `EtcdLockServer` crd printed by command `kubectl get etcdlockservers --output yaml`:
```yaml
apiVersion: planetscale.com/v2                                                                                                                                 
kind: EtcdLockserver                                                                                                                                           
metadata:                                                                                                                                                                                                                                                                          
  ...                                                                                                                  
spec:                                                                                                                                                          
  createClientService: true                                                                                                                                    
  createPDB: true                                                                                                                                              
  createPeerService: true                                                                                                                                      
  dataVolumeClaimTemplate:                                                                                                                                     
    accessModes:                                                                                                                                               
    - ReadWriteOnce                                                                                                                                            
    dataSource: null                                                                                                                                           
    resources:                                                                                                                                                 
      requests:                                                                                                                                                
        storage: 20Gi                                                                                                                                          
  image: quay.io/coreos/etcd:v3.3.13                                                                                                                           
  resources:                                                                                                                                                   
    limits:                                                                                                                                                    
      memory: 256Mi                                                                                                                                            
    requests:                                                                                                                                                  
      cpu: 100m                                                                                                                                                
      memory: 256Mi
```
however the generated PVC spec still has a default storage size `1Gi`:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  ...
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
