### ISSUE TITLE
Ability to set database's user authorization for allowing access to specific tables

### ISSUE THREAD

**Issue by maZahaca** [planetscale/vitess-operator#171]
Vitess topic described in here: https://vitess.io/docs/user-guides/configuration-advanced/authorization/

I was unable to find a description for vitess-operator to do that.

**Comment by prime-minister-of-fun** [comment]
Because there isn't one.  AFAICT, there are two keys, EXTRAMOUNTS EXTRAMOUNTPOINTS to point vtgate at a flat file that stores the permissions.  

There might be some other mechanism to generate the flat file inside the nodes, but I cannot find it and it is not documented.   Maybe I am missing it because I am new to Kubernetes.

**Comment by prime-minister-of-fun** [comment]
I finally figured this out because the answer was in the vitess slack channel.  You should probably subscribe to it if you want to speed up figuring this system out.  

This works for a configMap with a single key:

```
            extraVolumes:
            - name: acl-config
              configMap:
                name: "acl"

            extraVolumeMounts:
            - name: acl-config
              mountPath: /conf


```
There are options for selecting specific keys that are documented on the Kubernettes side.  I spent enough time on it, already.

Here's an example using secrets.  The indents might be wrong.

```
            extraVolumes:
            - name: acl-config
               secret:
                items:
                - path: acl.json
                  key: acl.json
                secretName: edify-db-cluster-config

```
