### ISSUE TITLE
extraVolumeMounts on vitessOrchestrator initContainer doesn't mount volumes 

### ISSUE THREAD

**Issue by prime-minister-of-fun** [planetscale/vitess-operator#210]
I realize this is beta software.  It needs some attention at some point.

Using the simplest config possible, initContainer doesn't mount volumes specified under the extraVolumeMounts.
excerpts of the deployment below.  Spacing might be wrong here due to copy/paste, but correct in the config.  I'm using this URL as documentation: https://vitess-operator.planetscale.dev/api/#planetscale.com/v2.VitessOrchestratorSpec
```
spec:
  vitessDashboard:
    replicas: 1
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 75m
        memory: 256Mi
```
next section: 

```
keyspaces:
- name: demoDB
    vitessOrchestrator:
      extraLabels:
        planetscale.com/component: vtorc
      configSecret:
        name: orc-config-80x
        key: orc_config.json
     initContainer:
        name: setup
        command: ["/bin/sh", "-c"]
        args: ["ls -l /"]
        extraVolumeMounts:
        - name: "orc-configs"
          mountPath: "/pickup"
        - name: "what"
          mountPath: /conf
      extraVolumeMounts:
       - name: "orc-configs"
          mountPath: "/pickup"
       - name: "what"
          mountPath: /conf
     extraVolumes:
      - name: "orc-configs"
         configMap:
          name: "orc-config"
      - name: "what"
        emptyDir: {}
```

The initContainer is created, but doesn't mount /pickup or /conf.  Here's the log from the init container.
drwxr-xr-x   1 root   root   214 Apr 27 19:40 bin
drwxr-xr-x   2 root   root     6 Mar 19 23:44 boot
drwxr-xr-x   5 root   root   360 Jul  2 02:15 dev
drwxr-xr-x   1 root   root    66 Jul  2 02:15 etc
drwxr-xr-x   2 root   root     6 Mar 19 23:44 home
drwxr-xr-x   1 root   root    56 Apr 27 19:39 lib
drwxr-xr-x   2 root   root    34 Apr  8 00:00 lib64
drwxr-xr-x   2 root   root     6 Apr  8 00:00 media
drwxr-xr-x   2 root   root     6 Apr  8 00:00 mnt
drwxr-xr-x   2 root   root     6 Apr  8 00:00 opt
dr-xr-xr-x 246 root   root     0 Jul  2 02:15 proc
drwx------   2 root   root    37 Apr  8 00:00 root
drwxr-xr-x   1 root   root    21 Jul  2 02:15 run
drwxr-xr-x   1 root   root    20 Apr 27 19:39 sbin
drwxr-xr-x   2 root   root     6 Apr  8 00:00 srv
dr-xr-xr-x  13 root   root     0 Jul  2 02:14 sys
drwxrwxrwt   1 root   root     6 Apr 27 19:40 tmp
drwxr-xr-x   1 root   root    81 Apr  8 00:00 usr
drwxr-xr-x   1 root   root    17 Apr  8 00:00 var
drwxr-xr-x   1 vitess vitess  21 Jul  2 02:15 vt

Meanwhile, the vtorc container mounts both /pickup and /conf.
