### ISSUE TITLE
vitessOrchestrator complete support for command: and args: key words

### ISSUE THREAD

**Issue by prime-minister-of-fun** [planetscale/vitess-operator#211]
I realize vtorc is beta software and this might be a feature request rather than a bug.

Using  _command:_ and _args:_ keywords to copy a file before vtorc runs doesn't work.  However, _command:_ and _args:_ work under initContainer.  Below is an example that generates an initContainer log with the output of "ls -l /"

```
spec:
  vitessDashboard:
    replicas: 1
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 75m
        memory: 256Mi
```
next section: 

```
keyspaces:
- name: demoDB
    vitessOrchestrator:
      extraLabels:
        planetscale.com/component: vtorc
      configSecret:
        name: orc-config-80x
        key: orc_config.json
     initContainer:
        name: setup
        command: ["/bin/sh", "-c"]
        args: ["ls -l /"]
     extraVolumes:
      - name: "orc-configs"
         configMap:
          name: "orc-config"
      - name: "what"
        emptyDir: {}
```
Based on how initContainer works, the expected results of the below config  should be the results of "ls -l /" in the vtorc pod log.  The actual results are that the results of "ls -l /" are NOT logged.  Only Vtorc is logging.  I assume that means command: and args: are not being honored at the vitessOrchestrator level.  The config I tried is below:

```
keyspaces:
- name: demoDB
    vitessOrchestrator:
      extraLabels:
        planetscale.com/component: vtorc
      configSecret:
        name: orc-config-80x
        key: orc_config.json
      command: ["/bin/sh", "-c"]
      args: ["ls -l /"]
      extraVolumeMounts:
        - name: "orc-configs"
          mountPath: "/pickup"
        - name: "what"
          mountPath: /conf
      extraVolumeMounts:
       - name: "orc-configs"
          mountPath: "/pickup"
       - name: "what"
          mountPath: /conf
     extraVolumes:
      - name: "orc-configs"
         configMap:
          name: "orc-config"
      - name: "what"
        emptyDir: {}
```
