### ISSUE TITLE
Pending backup initialization pods deadlock clusters when using the `toplvm` dynamic provisioner

### ISSUE THREAD

**Issue by streadway** [planetscale/vitess-operator#221]
### Overview

New cluster tablets do not start serving when backup initialization pods cannot start to take the initial backup.

Vttablet pods are scheduled on nodes with a local data volume template and are waiting for an initial backup.

Vtbackup init pods are scheduled on nodes and Pending in the pre-bind volume phase. The storage provisioner cannot create volumes for the scheduled node, leaving the the vtbackup pods Pending.

This affects clusters that use dynamic local storage provisioned data volumes on a cluster with volumes available only on some nodes. This is experienced with [`topolvm`](https://github.com/topolvm/topolvm) where some nodes in the cluster do not have an LVM Physical Volume for the provisioner.

#### Analysis

The vtbackup init pods are [reconciled before](https://github.com/planetscale/vitess-operator/blob/1aef31a78a616069f7fb31d9aefd5e396de474a7/pkg/controller/vitessshard/reconcile_backup_job.go#L114-L174) their data volume PVC. There is more than one condition that could prevent the PVC from provisioning a volume in the pre-bind phase, and we have observed "Pre-bind failed. No topology key found".

This differs from vttablet, where the pod is [reconciled after](https://github.com/planetscale/vitess-operator/blob/da7efd4c945193864f5996cb793055449c4de97a/pkg/controller/vitessshard/reconcile_tablets.go#L113-L259) the data volume PVC. This gives a chance for the external provisioner to influence the scheduling based on the PVC claim and node capacity. Tablets are scheduled successfully.

Pods without PVCs are [considered by topolvm](https://github.com/topolvm/topolvm/blob/main/docs/limitations.md#pod-without-pvc) but not supported.

#### Recommendation

Reconcile PVCs before Pods, in the same order for vtbackup and vttablet pods, when they share a data volume template.

#### Workarounds

* Delete the pods to be recreated after the PVC exists.

* Create the cluster with `initializeBackup: false`, then run `vtctl BackupShard` manually.

* Ensure every node in the cluster has a provisioner and the capacity for scheduled pod volumes.

* Enable Storage Capacity Tracking in Kubernetes >= 1.19 and Topolvm >= 0.8.4 so that Pods scheduled to nodes with unschedulable PVCs can get rescheduled to new nodes.

### Reproduction Steps (topolvm + vitess operator)

1. Setup a Vitess CRD+operator in a Kubernetes cluster with at least 2 nodes.

1. Deploy `topolvm` and run external provisioners on `example-node1` but not on `example-node2`.

1. Create a "local" storage class, using the WaitForFirstConsumer volume binding mode and the topolvm provisioner.

1. Create a cluster with:

```yaml
apiVersion: planetscale.com/v2
kind: VitessCluster
metadata:
  name: example
  namespace: vt-example
spec:
  backup:
    engine: xtrabackup
    locations:
    - name: gcs
      # Type doesn't matter for this issue
      gcs:
        authSecret:
          key: key.json
          name: backup-auth
        bucket: vitess-operator-backup-init-topolvm-issue
  keyspaces:
  - name: keyspace1
    partitionings:
    - equal:
        parts: 2
        shardTemplate:
          databaseInitScriptSecret:
            key: init_db.sql
            name: init-config
          replication:
            initializeBackup: true
            initializeMaster: true
            recoverRestartedMaster: true
          tabletPools:
          - cell: cell1
            type: replica
            replicas: 2
            backupLocationName: gcs
            dataVolumeClaimTemplate:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 10Mi
              storageClassName: local
            mysqld:
              resources: {}
            vttablet:
              resources: {}
  cells:
  - name: cell1
    gateway:
      replicas: 1
      resources: {}
      authentication:
        static:
          secret:
            name: vtgate
            key: users.json
```

1. With the following secrets/keys:

* `backup-auth/key.json` - GCP service account credentials - replace with your own.
* `init-config/init_db.sql` - default database initialization script.
* `vtgate/users.json` - default vtgate static authorization file.

#### Versions

```plain
kubernetes: 1.19.7
vitess: 10.0.1
vitess-operator: 2.4.0
vitess-operator operator-sdk: v0.16.0

topolvm: quay.io/topolvm/topolvm-with-sidecar:0.8.3
csi: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0
```

### Observations

Schedules the following pods:

```tsv
NAME                                                     READY   STATUS             RESTARTS   AGE
example-cell1-vtctld-30b77a3b-6cd48c9cb4-4ckgx           1/1     Running            6          34m
example-cell1-vtgate-5878cb1e-69f75b9546-9gmml           0/1     CrashLoopBackOff   5          8m4s
example-etcd-faf13de3-1                                  1/1     Running            5          34m
example-etcd-faf13de3-2                                  1/1     Running            5          34m
example-etcd-faf13de3-3                                  1/1     Running            5          34m
example-gcs-8bbc7eb3-vitessbackupstorage-subcontroller   1/1     Running            0          16m
example-keyspace1-80-x-vtbackup-init-cb2f81aa            0/1     Pending            0          33m
example-keyspace1-x-80-vtbackup-init-a9e8a6ee            0/1     Pending            0          33m
example-vttablet-cell1-0594325533-a04ab155               3/3     Running            1          34m
example-vttablet-cell1-0840121086-7f5eec15               3/3     Running            1          34m
example-vttablet-cell1-1199451902-7021fcd8               3/3     Running            1          34m
example-vttablet-cell1-4001313850-18fe025f               3/3     Running            1          34m
vitess-operator-6d9b44c6f4-zw585                         1/1     Running            0          37m
```

With the following PVCs:

```tsv
NAME                                            STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
example-etcd-faf13de3-1                         Bound     pvc-107bdce3-64b9-49ac-a22f-4f7297a09958   1Gi        RWO            standard       36m
example-etcd-faf13de3-2                         Bound     pvc-402042a9-34b5-4762-ac0b-d771bc89b335   1Gi        RWO            standard       36m
example-etcd-faf13de3-3                         Bound     pvc-2d09f5a2-f393-4ce5-81b6-d04f5c01b881   1Gi        RWO            standard       36m
example-keyspace1-80-x-vtbackup-init-cb2f81aa   Pending                                                                        local          36m
example-keyspace1-x-80-vtbackup-init-a9e8a6ee   Pending                                                                        local          36m
example-vttablet-cell1-0594325533-a04ab155      Bound     pvc-fa502fb0-7dc9-42ee-a9fb-e853dcca164f   1Gi        RWO            local          36m
example-vttablet-cell1-0840121086-7f5eec15      Bound     pvc-e016d8fd-7475-4847-93aa-b40fc7adc509   1Gi        RWO            local          36m
example-vttablet-cell1-1199451902-7021fcd8      Bound     pvc-301e5e5d-695a-484c-ace3-1037124be9bc   1Gi        RWO            local          36m
example-vttablet-cell1-4001313850-18fe025f      Bound     pvc-f9b2fdbb-02e0-4560-b6cc-e5f2e883305c   1Gi        RWO            local          36m
```

Describing one of the pending backup init PVCs:

```plain
Name:          example-keyspace1-80-x-vtbackup-init-cb2f81aa
Namespace:     vt-example
StorageClass:  local
Status:        Pending
Volume:        
Labels:        backup.planetscale.com/location=gcs
               backup.planetscale.com/type=init
               planetscale.com/cluster=example
               planetscale.com/component=vtbackup
               planetscale.com/keyspace=keyspace1
               planetscale.com/shard=80-x
Annotations:   volume.beta.kubernetes.io/storage-provisioner: topolvm.cybozu.com
               volume.kubernetes.io/selected-node: example-node2
Finalizers:    [kubernetes.io/pvc-protection topolvm.cybozu.com/pvc]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    example-keyspace1-80-x-vtbackup-init-cb2f81aa
Events:
  Type     Reason                Age                    From                                                                                         Message
  ----     ------                ----                   ----                                                                                         -------
  Normal   WaitForPodScheduled   38m                    persistentvolume-controller                                                                  waiting for pod example-keyspace1-80-x-vtbackup-init-cb2f81aa to be scheduled
  Warning  ProvisioningFailed    16m (x14 over 38m)     topolvm.cybozu.com_topolvm-controller-5b96bbfc54-4zp58_2145e7a3-1e48-4305-a167-63da9774bbda  failed to provision volume with StorageClass "local": error generating accessibility requirements: no topology key found on CSINode example-node2
  Normal   ExternalProvisioning  3m30s (x142 over 38m)  persistentvolume-controller                                                                  waiting for a volume to be created, either by external provisioner "topolvm.cybozu.com" or manually created by system administrator
  Normal   Provisioning          95s (x18 over 38m)     topolvm.cybozu.com_topolvm-controller-5b96bbfc54-4zp58_2145e7a3-1e48-4305-a167-63da9774bbda  External provisioner is provisioning volume for claim "vt-example/example-keyspace1-80-x-vtbackup-init-cb2f81aa"
```

The CSINode for `example-node2` **does not have topolvm drivers** - the topolvm provisioner is not running on this node.

```plain
Name:               example-node2
Labels:             <none>
Annotations:        <none>
CreationTimestamp:  Tue, 27 Apr 2021 10:27:17 +0200
Spec:
  Drivers:
    rook-ceph.rbd.csi.ceph.com:
      Node ID:  example-node2
Events:         <none>
```

Describing a successfully bound PVC for a vttablet succeeded to provision a PV:

```plain
Name:          example-vttablet-cell1-0594325533-a04ab155
Namespace:     vt-example
StorageClass:  local
Status:        Bound
Volume:        pvc-fa502fb0-7dc9-42ee-a9fb-e853dcca164f
Labels:        planetscale.com/cell=cell1
               planetscale.com/cluster=example
               planetscale.com/component=vttablet
               planetscale.com/keyspace=keyspace1
               planetscale.com/shard=80-x
               planetscale.com/tablet-index=1
               planetscale.com/tablet-type=replica
               planetscale.com/tablet-uid=594325533
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: topolvm.cybozu.com
               volume.kubernetes.io/selected-node: example-node1
Finalizers:    [kubernetes.io/pvc-protection topolvm.cybozu.com/pvc]
Capacity:      1Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    example-vttablet-cell1-0594325533-a04ab155
Events:
  Type    Reason                 Age   From                                                                                         Message
  ----    ------                 ----  ----                                                                                         -------
  Normal  WaitForFirstConsumer   45m   persistentvolume-controller                                                                  waiting for first consumer to be created before binding
  Normal  Provisioning           45m   topolvm.cybozu.com_topolvm-controller-5b96bbfc54-4zp58_2145e7a3-1e48-4305-a167-63da9774bbda  External provisioner is provisioning volume for claim "vt-example/example-vttablet-cell1-0594325533-a04ab155"
  Normal  ExternalProvisioning   45m   persistentvolume-controller                                                                  waiting for a volume to be created, either by external provisioner "topolvm.cybozu.com" or manually created by system administrator
  Normal  ProvisioningSucceeded  45m   topolvm.cybozu.com_topolvm-controller-5b96bbfc54-4zp58_2145e7a3-1e48-4305-a167-63da9774bbda  Successfully provisioned volume pvc-fa502fb0-7dc9-42ee-a9fb-e853dcca164f
```

The CSINode `example-node1` for the vttablet PVC has the topolvm driver.

```plain
Name:               example-node1
Labels:             <none>
Annotations:        <none>
CreationTimestamp:  Thu, 19 Aug 2021 18:12:16 +0200
Spec:
  Drivers:
    topolvm.cybozu.com:
      Node ID:        example-node1
      Topology Keys:  [topology.topolvm.cybozu.com/node]
    rook-ceph.rbd.csi.ceph.com:
      Node ID:  example-node1
Events:         <none>
```

The vttablet logs are deadlocked for a backup before serving:

```plain
I0913 14:21:42.733230       1 restore.go:177] No backup found. Waiting 10s (from -wait_for_backup_interval flag) to check again.
```
