### ISSUE TITLE
[Feature Request] Allow setting mysqld-exporter resources

### ISSUE THREAD

**Issue by gairadzi** [planetscale/vitess-operator#311]
The resources for the mysqld-exporter container are currently hard-coded in the operator, we would like to able to change them in the shard template resource.

**Comment by subnix** [comment]
Looks like closed in #494

**Comment by GenLN** [comment]
Hi @subnix 
I think something isn't working as expected. Even if I don't define limit on CPU it will assign CPU limit to 100m. As we have defined resources like 

```
mysqldExporter:
  resources:
    limits:
      memory: 125Mi
    requests:
      cpu: 100m
      memory: 50Mi
```
