### ISSUE TITLE
Feature Request: Allow more than one VitessShardTabletPool with a certain tablet type in a given cell

### ISSUE THREAD

**Issue by yoheimuta** [planetscale/vitess-operator#428]
### Feature Description

We want to create [more than one VitessShardTabletPool with a certain tablet type in a given cell](https://github.com/planetscale/vitess-operator/blob/685391b42447b97e1e9dcb7640ced2a8ca01c291/pkg/apis/planetscale/v2/vitessshard_types.go#L105-L116).
This would allow us to support multiple unmanaged MySQL replicas with minimal changes like the one below.

```yaml
apiVersion: planetscale.com/v2
kind: VitessCluster
metadata:
  name: example
spec:
  cells:
    - name: zone1
  keyspaces:
    - name: unsharded
      partitionings:
      - equal:
          parts: 1
          shardTemplate:
            tabletPools:
              - cell: zone1
                type: externalreplica
                replicas: 2
                vttablet:
                externalDatastore:
                  host: replica-host-1
              - cell: zone1
                type: externalreplica
                replicas: 2
                vttablet:
                externalDatastore:
                  host: replica-host-2
```

With this feature, we don't have to set up a (vtgate, vttablet) pair for each additional MySQL replica like the following, which requires client redirection to a different endpoint.

```yaml
apiVersion: planetscale.com/v2
kind: VitessCluster
metadata:
  name: example
spec:
  cells:
    - name: zone1
    - name: zone2
  keyspaces:
    - name: unsharded
      partitionings:
        - equal:
            parts: 1
            shardTemplate:
              tabletPools:
                - cell: zone1
                  type: externalreplica
                  replicas: 2
                  vttablet:
                  externalDatastore:
                    host: replica-host-1
                - cell: zone2
                  type: externalreplica
                  replicas: 2
                  vttablet:
                  externalDatastore:
                    host: replica-host-2
```

### Use Case(s)

- When you want to build a redundant system with unmanaged tablets

### Discussion

- https://vitess.slack.com/archives/CNE9WP677/p1685090821858559
- https://vitess.slack.com/archives/CNE9WP677/p1685083619890119
