### ISSUE TITLE
Add custom annotations to PVC

### ISSUE THREAD

**Issue by luismacosta** [planetscale/vitess-operator#484]
Hello,

I'm using aws-ebs-csi-driver to create volumes in aws
In order to [modify volumes  iops/throughput](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/modify-volume.md) I would like to add annotations to the vttablets PVC. From what I can see in the CR, [dataVolumeClaimTemplate](https://github.com/planetscale/vitess-operator/blob/main/deploy/crds/planetscale.com_vitessclusters.yaml#L518) has no property for annotations.

**Comment by frouioui** [comment]
Do you have an example of how you want to use these annotations?

**Comment by luismacosta** [comment]
> Do you have an example of how you want to use these annotations?

Hello @frouioui 

In [dataVolumeClaimTemplate](https://github.com/planetscale/vitess-operator/blob/main/deploy/crds/planetscale.com_vitessclusters.yaml#L992), add:

```yaml
annotations:
 additionalProperties:
   type: string
 type: object
```

As example you may check [aws-ebs-csi-driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/modify-volume.md)

```yaml
  annotations:
	ebs.csi.aws.com/volumeType: "io2"
	ebs.csi.aws.com/iops: "4000"
```
