### ISSUE TITLE
Help Finding Docs related to operator arguments and env

### ISSUE THREAD

**Issue by FarhanMS123** [planetscale/vitess-operator#571]
Hi! I comes from vitess sites and currently proof-reading examples operator for Deploy Kubernetes. In short, I find there are some ENV and Args for a vitess-operator deployment in [`operator.yaml`](https://github.com/vitessio/vitess/blob/1c7632f16c3f2fc94a0107d89b45c1f03aaac3fe/examples/operator/operator.yaml#L6862).

I tried to search any [API documentation](https://github.com/planetscale/vitess-operator/blob/main/docs/api.md), but those all just related to CRDs, not the operator itself. For arguments, I actually could execute `vitess-operator --help` in container shell, but I believe this is not a best practice, I also not wish to dig into the code itself. And there are also ENV already defined in the yaml.

```yaml
containers:
  - args:
      - --logtostderr
      - -v=4
    command:
      - vitess-operator
    env:
      - name: WATCH_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: PS_OPERATOR_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: PS_OPERATOR_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: OPERATOR_NAME
        value: vitess-operator
    image: planetscale/vitess-operator:v2.13.0
```

My question, Is there any official documentation regarding vitess-operator arguments and the ENV variables? Or maybe something like `types.d.ts` but for Go. I mean I don't want to dig it too deeper into the code just to know the Env and Args, and doing `--help` directly is still not a best practice.
