### ISSUE TITLE
VTTablet unable to start when using `externalDatastore`

### ISSUE THREAD

**Issue by arvindkalra08** [planetscale/vitess-operator#596]
When we try to create a keyspace using a tablet with external datasource by providing the `externalDatastore` property in YML, the `vttablet` pod is unable able to spawn up.

My keyspace section of YML looks the following:
```
- name: email_service_legacy
    turndownPolicy: Immediate
    databaseName: email_service
    partitionings:
      - equal:
          parts: 1
          shardTemplate:
            databaseInitScriptSecret:
              name: example-cluster-config
              key: init_db.sql
            tabletPools:
              - cell: zone1
                type: externalmaster
                replicas: 1
                vttablet:
                  extraFlags:
                    disable_active_reparents: "true"
                    db_charset: utf8mb4
                  resources:
                    limits:
                      memory: 256Mi
                    requests:
                      cpu: 100m
                      memory: 256Mi
                externalDatastore:
                  user: ***
                  host: ***
                  port: 3306
                  database: email_service
                  credentialsSecret:
                    name: example-cluster-config
                    key: external_users.json
```

And following is the error log from the `vttablet` pod for the same:

```
unknown flag: --vreplication_tablet_type
```

Can someone help debug this? Let me know if you need more information.

I am using these images:
```
images:
    vtctld: vitess/lite:latest
    vtadmin: vitess/vtadmin:latest
    vtgate: vitess/lite:latest
    vttablet: vitess/lite:latest
    vtbackup: vitess/lite:latest
    vtorc: vitess/lite:latest
    mysqld:
      mysql80Compatible: mysql:8.0.30
    mysqldExporter: prom/mysqld-exporter:v0.11.0
```
