### ISSUE TITLE
Unable to use node labels to schedule vttablet pods.

### ISSUE THREAD

**Issue by bluecrabs007** [planetscale/vitess-operator#604]
Currently, the operator uses a standard NodeSelector `topology.kubernetes.io/zone` which is exposed via the `spec.Zone` in the `VitessCluster` custom resource.
This means, the vttablets' pod spec's nodeSelector can only specify a label, such as, `topology.kubernetes.io/zone=<value>` and nothing else.  [Reference](https://github.com/planetscale/vitess-operator/blob/f36568a7ba67422adac8cc33cde4898d0b908294/pkg/operator/vttablet/pod.go#L359-L377)
For usecases where we want to direct the VTOP to schedule the vttablets onto nodes that have a specific label, for example `hardware=intel`, this is currently not possible. 

Would be nice if the operator exposes a way to pass arbitary set of labels via the VTTablet's nodeSelector
https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector

**Comment by GenLN** [comment]
but you can use affinty inside tablet pools like 
```
keyspaces:
- name: keyspace1
  ....
  partitionings:
  - equal:
      parts: 2
      shardTemplate:
        databaseInitScriptSecret:
          name: init
          key: init_db.sql
        tabletPools:
        - cell: cellName
          affinity:
            podAntiAffinity:
            nodeAffinity:
          type: replica
          replicas: 3
          ....
```
