### ISSUE TITLE
After configuring TabletPool Affinity, the Zone configuration will become invalid

### ISSUE THREAD

**Issue by chhan-coupang** [planetscale/vitess-operator#649]
Our Vitess will configure the following affinity, but this will cause the Zone to no longer take effect, causing the zone to not be as expected.
```yaml
          tabletPools:
          - affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                  - matchExpressions:
                    - key: alpha.eksctl.io/nodegroup-name
                      operator: In
                      values:
                      - vitess-20
            cell: ap2d
```

The relevant code implementation is that after specifying any affinity, the default rule will no longer take effect.
Can we open **nodeSelector** or other methods/parameters to make custom affinity and zone configuration take effect at the same time?
https://github.com/planetscale/vitess-operator/blob/f36568a7ba67422adac8cc33cde4898d0b908294/pkg/operator/vttablet/pod.go#L359-L377

Reference: #604

**Comment by chhan-coupang** [comment]
**vttablet** can be replaced by the following method, but be careful to manually set different zones.
Others like **vtgate/vtctld/vtorc** cannot be configured in this way because they do not distinguish zones on the vitescluster object.
```yaml
   affinity:
     nodeAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
         - matchExpressions:
           - key: alpha.eksctl.io/nodegroup-name
             operator: In
             values:
             - vitess-test-bcd
           - key: topology.kubernetes.io/zone
             operator: In
             values:
             - ap-northeast-2b
```
