### ISSUE TITLE
DATA_SOURCE_NAME is no longer supported for mysqld_exporter

### ISSUE THREAD

**Issue by Danmark** [planetscale/vitess-operator#696]
Vitess operator uses the env-var DATA_SOURCE_NAME to propagate connection details to mysqld_exporter.
That is not supported in mysqld_exporter since 2023-06-16

https://github.com/prometheus/mysqld_exporter/releases/tag/v0.15.0

https://github.com/planetscale/vitess-operator/blob/373c79103c49280059fe16f8edd7a41b6bf6a76c/pkg/operator/vttablet/env_vars.go#L49

**Comment by frouioui** [comment]
Hi, keeping this environment variable set on newer versions of the mysqld_exporter should be a no-op.

To replace its functionality, these extra flags can be set on the `mysqldExporter`:
```
            mysqldExporter:
              extraFlags:
                config.my-cnf: "/vt/config/mycnf/socket.cnf"
                mysqld.username: "vt_dba"
```

These two strings are constant in the operator codebase, and could be used safely to authenticate mysqld_exporter.
