### ISSUE TITLE
VitessBackup unknown flag s3_backup_aws_min_partsize

### ISSUE THREAD

**Issue by steache** [planetscale/vitess-operator#701]
Hello,

after upgrading to latest vitess-operator (2.15.0) backups are no longer working.

```
    - name: vitess-operator
      image: planetscale/vitess-operator:v2.15.0
      command:
        - vitess-operator
      args:
        - '--logtostderr'
        - '-v=4'
        - '--backup_storage_implementation=s3'
        - '--s3_backup_aws_endpoint=xxx'
        - '--s3_backup_aws_min_partsize=0'
        - '--s3_backup_aws_region=nbg1'
        - '--s3_backup_force_path_style=false'
        - '--s3_backup_storage_bucket=xxx'
        - '--s3_backup_storage_root=xxx'
```

- https://github.com/vitessio/vitess/pull/17171
- https://github.com/search?q=repo%3Aplanetscale%2Fvitess-operator%20s3_backup_aws_min_partsize&type=code
- https://github.com/planetscale/vitess-operator/blame/373c79103c49280059fe16f8edd7a41b6bf6a76c/pkg/operator/vitessbackup/storage_s3.go#L34

I don't see a way to disable this flag from crds/config, so every backup schedule we had is not working anymore. :D 
For now, I've removed the flag & created my own image.

Thank you for any help :)
